### ISSUE TITLE
Скласти блок контактної інформації

### ISSUE THREAD

**Issue by zhyzhkoslava** [zhyzhkoslava/homepage#6]
Посилання на соцмережі (Facebook чи Instagram, тощо), номер телефону чи адреса електронної скриньки, тощо. Може не всі лінки в світі, а тільки ті, що дійсно доречні.

**Comment by slyusarchyn** [comment]
Люблю тебе, зайка

**Comment by zhyzhkoslava** [comment]
Дякую
